language: cpp

matrix:
  include:
    - os: linux
      cache:
        directories:
          - /var/cache/apt/archives/*.deb
      compiler: gcc
      sudo: require
      dist: trusty
    - os: osx

script:
  - ./.travis/build.sh

before_deploy:
  - git fetch --unshallow
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then packagetype=appimage ; fi
  - if [[ $TRAVIS_OS_NAME == 'osx'   ]]; then packagetype=macos ; fi
  - gittag=$(git describe --tags --abbrev=0)
  - today=$(date +"%Y-%m-%d")
  - gitrev=$(git log -1 --format="%h")
  - gitdate=$(git log -1 --format="%aI")
  - cat .travis/bintray.json.in |
    sed -e "s,@BINTRAY_REPO@,$packagetype,g"
        -e "s,@PKGVER@,$gittag,g"
        -e "s,@GITTAG@,$gittag,g"
        -e "s,@TODAY@,$today,g"
        -e "s,@GITREV@,$gitrev,g"
        -e "s,@GITDATE@,$gitdate,g"
        > .travis/bintray.json

deploy:
  provider: bintray
  file: .travis/bintray.json
  on:
    tags: true
  user:
    secure: "VkihJWmsRrCJaoN0TDEQYUxA+BzUr62x+zG+5WcUAU0jMhQjGa/ZIHhKPaIyx9lPZxQRvP2wtU70gMk5fnjD07TlkWfzskhIdjVZQViiu+0QDSSASTiyRFHx5MeVvV3v0nJKJssIzp9l4AG8fhnTXue6h35GpfGHrDE7+ol+fdIZM/E2dDm7Pt/ONS/LFcSiE3oB++glTE/z9YGIAXKjZgh8A0GicJNyvA+UgVd5ir0JspCnXN3TRnL6tm4upFhxeNII+O9SDdVQaQ055BicJiDdrjQcmdwRx3rzsT21mZ3xQqA5O2M2Hv2BQgZXaEtL1pf0udmmWlHcOyKVD7+UJmQqVi+oPO82GX0Zjr3DPHUUNHA2ZOTzVLOJz2G7VK+yZ6TSIQPSR3Lzlr09zsuHpnyuhH4IRl5HfIj+HAvhT/yFgZgaCqpDwxZFU67n49EMDjb42bhpNzBK/210VyCkIJIrAOikaeCZ0PgiwIuRJ3xMFr3vkQwePTswhkwGtw5SgWqb17WXX9tqwWvzS39nSLIWTXai5mHHm8CZTwbanJDafIRPuWaj5JwvpNMJr19vI8x4r1qJ1+aNnnjLT5Zk6UtPc/PkIOwTiB7+1WD3C1vqWWqa/KH9YPddcf7I58MCigiGSeOsjyh5SMFoyoGbk1zA8F+ihI35FOyaW+3czr4="
  key:
    secure: "NgyGHAg1dvzeT9oNq3buZglc9Dps5B7fuim1Xg2mH+OoWWL9GXRNJngEmER/NmzB4KYq6VqvdfdQnxgCnyLR/86u/t5tRe5bOYt5YLOGsOCpognEoGc9hHaIX0u0Hro/ApycRs5XsWQMt6G9Ih5zzbd4DM31Rn1HELFiIF7PMZCac18Q3sW1mfpivpc01X6EyDfniME1C0is+DVquJXGLZ2zWPx8UTypBsledBn5bFcwUkPJVlr0ofAqOcP/muVjjG6zsbqT6zx5CdjCaLtqRXLiMMB2i67TkmT4U2No+p1Qg19zD7pjsd9N/7CINq29yLlbsahxZr0ItE3Zl5D4JrZTpXbSXlH0Rfljsafo0dsIJCcJnqZHLLoJg0IWFOOrcCZ/qgH9aAyXKFahkPWorHFAyVffDQYwytOy0KCMs+aZE+VknQjmn/+rZKo4Yal2yHXtKgnra8jk8zyL50ZZ7fj6veKl1o5TP1qXwMYP11FmZ5B6x6svH6w8hr7lDAztFtN3P5w/aBHReSsW7HyqO9Jref9Ww3WjdPfbRg8TrgmSV4p3KLw1boHVbZCcp30Ew5y9TwjdhA2cbCoc/qaZQj+Dj823j6q+mREctetR7Ucj2Ma6fA0GVm5M/12w1DjSAVIKrHCr6jodWYcpaozow8EL5HC5eoeJTOWL91PEVd0="

notifications:
  email: false
  slack: lirios:fdUqVmPzqPskEL1UBhqapZ0w
